setlocal nofoldenable
setlocal foldmethod=expr
setlocal foldexpr=nvim_treesitter#foldexpr()
setlocal foldnestmax=10
setlocal foldlevel=2
setlocal textwidth=80
setlocal tabstop=2
setlocal expandtab
setlocal shiftwidth=2
